[languageServers.codebook]
enabled = false
cmd = ["codebook-lsp", "serve"]
languages = ["c", "css", "gitcommit", "go", "haskell", "html", "java", "javascript", "javascriptreact", "lua", "markdown", "php", "python", "ruby", "rust", "swift", "toml", "text", "typescript", "typescriptreact", "zig"]
workspaceMarkers = [".git", "codebook.toml", ".codebook.toml"]
