[languageServers.cssmodules_ls]
enabled = false
cmd = ["cssmodules-language-server"]
languages = ["javascript", "javascriptreact", "typescript", "typescriptreact"]
workspaceMarkers = ["package.json"]
