[languageServers.dexter]
enabled = false
cmd = ["dexter", "lsp"]
languages = ["elixir", "eelixir", "heex"]
workspaceMarkers = [".dexter/dexter.db", ".dexter.db", ".git", "mix.exs"]
initializationOptions = { followDelegates = true }
