[languageServers.docker_compose_language_service]
cmd = ["docker-compose-langserver", "--stdio"]
languages = ["yaml.docker-compose"]
rootMarkers = ["docker-compose.yaml", "docker-compose.yml", "compose.yaml", "compose.yml"]
