[languageServers.docker_compose_language_service]
enabled = false
cmd = ["docker-compose-langserver", "--stdio"]
languages = ["yaml.docker-compose"]
workspaceMarkers = ["docker-compose.yaml", "docker-compose.yml", "compose.yaml", "compose.yml"]
