[languageServers.ember]
enabled = false
cmd = ["ember-language-server", "--stdio"]
languages = ["handlebars", "typescript", "javascript", "typescript.glimmer", "javascript.glimmer"]
rootMarkers = ["ember-cli-build.js", ".git"]
