[languageServers.fortls]
enabled = false
cmd = ["fortls", "--notify_init", "--hover_signature", "--hover_language=fortran", "--use_signature_help"]
languages = ["fortran"]
workspaceMarkers = [".fortls", ".fortlsrc", ".fortls.json", ".git"]
