[languageServers.fsharp_language_server]
enabled = false
cmd = ["dotnet", "FSharpLanguageServer.dll"]
languages = ["fsharp"]
workspaceMarkers = ["*.sln", "*.fsproj", ".git"]
initializationOptions = { AutomaticWorkspaceInit = true }
