[languageServers.gitlab_ci_ls]
enabled = false
cmd = ["gitlab-ci-ls"]
languages = ["yaml.gitlab"]
workspaceMarkers = [".git", ".gitlab*"]
initializationOptions = { cache_path = "/Users/atusy/.cache/gitlab-ci-ls/", log_path = "/Users/atusy/.cache/gitlab-ci-ls//log/gitlab-ci-ls.log" }
