[languageServers.gradle_ls]
enabled = false
cmd = ["gradle-language-server"]
languages = ["groovy"]
workspaceMarkers = ["settings.gradle", "build.gradle"]
initializationOptions = { settings = { gradleWrapperEnabled = true } }
