# WARN: handlers (client-side LSP handlers) were dropped
[languageServers.grammarly]
enabled = false
cmd = ["grammarly-languageserver", "--stdio"]
languages = ["markdown"]
workspaceMarkers = [".git"]
initializationOptions = { clientId = "client_BaDkMgx4X19X9UxxYRCXZo" }
