[languageServers.graphql]
enabled = false
cmd = ["graphql-lsp", "server", "-m", "stream"]
languages = ["graphql", "typescriptreact", "javascriptreact"]
workspaceMarkers = [".graphqlrc*", ".graphql.config.*", "graphql.config.*"]
