[languageServers.harper_ls]
cmd = ["harper-ls", "--stdio"]
languages = ["asciidoc", "c", "cpp", "cs", "gitcommit", "go", "html", "java", "javascript", "lua", "markdown", "nix", "python", "ruby", "rust", "swift", "tex", "toml", "typescript", "typescriptreact", "haskell", "cmake", "typst", "php", "dart", "clojure", "sh"]
rootMarkers = [".harper-dictionary.txt", ".git"]
