[languageServers.intelephense]
enabled = false
cmd = ["intelephense", "--stdio"]
languages = ["php"]
workspaceMarkers = [".git", "composer.json"]
settings = { intelephense = { telemetry = { enabled = false } } }
