[languageServers.jls]
enabled = false
cmd = ["jls"]
languages = ["java"]
rootMarkers = ["pom.xml", "build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts", "WORKSPACE", "WORKSPACE.bazel", ".java-version"]
