[languageServers.kotlin_language_server]
enabled = false
cmd = ["kotlin-language-server"]
languages = ["kotlin"]
workspaceMarkers = ["settings.gradle", "settings.gradle.kts", "build.xml", "pom.xml", "build.gradle", "build.gradle.kts"]
