[languageServers.kotlin_lsp]
enabled = false
cmd = ["intellij-server", "--stdio"]
languages = ["kotlin"]
rootMarkers = ["settings.gradle", "settings.gradle.kts", "pom.xml", "build.gradle", "build.gradle.kts", "workspace.json"]
