[languageServers.matlab_ls]
enabled = false
cmd = ["matlab-language-server", "--stdio"]
languages = ["matlab"]
workspaceMarkers = [".git"]
settings = { MATLAB = { indexWorkspace = true, installPath = "", matlabConnectionTiming = "onStart", telemetry = true } }
