[languageServers.msbuild_project_tools_server]
enabled = false
cmd = ["dotnet", "MSBuildProjectTools.LanguageServer.Host.dll"]
languages = ["msbuild"]
workspaceMarkers = ["*.sln", "*.slnx", "*.*proj", ".git"]
