[languageServers.nextflow_ls]
enabled = false
cmd = ["nextflow-language-server"]
languages = ["nextflow"]
rootMarkers = ["nextflow.config", ".git"]
settings = { nextflow = { files = { exclude = [".git", ".nf-test", "work"] } } }
