[languageServers.perlls]
enabled = false
cmd = ["perl", "-MPerl::LanguageServer", "-e", "Perl::LanguageServer::run", "--", "--port 13603", "--nostdio 0"]
languages = ["perl"]
workspaceMarkers = [".git"]
settings = { perl = { fileFilter = [".pm", ".pl"], ignoreDirs = ".git", perlCmd = "perl", perlInc = " " } }
