[languageServers.prismals]
enabled = false
cmd = ["prisma-language-server", "--stdio"]
languages = ["prisma"]
workspaceMarkers = [".git", "package.json"]
settings = { prisma = { prismaFmtBinPath = "" } }
