[languageServers.remark_ls]
enabled = false
cmd = ["remark-language-server", "--stdio"]
languages = ["markdown"]
rootMarkers = [".remarkrc", ".remarkrc.json", ".remarkrc.js", ".remarkrc.cjs", ".remarkrc.mjs", ".remarkrc.yml", ".remarkrc.yaml", ".remarkignore"]
