[languageServers.rescriptls]
enabled = false
cmd = ["rescript-language-server", "--stdio"]
languages = ["rescript"]
workspaceMarkers = ["bsconfig.json", "rescript.json", ".git"]
initializationOptions = { extensionConfiguration = { allowBuiltInFormatter = true, askToStartBuild = false, cache = { projectConfig = { enabled = true } }, codeLens = true, incrementalTypechecking = { acrossFiles = true, enable = true }, inlayHints = { enable = true } } }
