# WARN: root_dir was a dynamic Lua function (dynamic root detection); approximate with `rootMarkers` if the default (client root) is wrong
[languageServers.rnix]
cmd = ["rnix-lsp"]
languages = ["nix"]
