# WARN: get_language_id (Lua function) was dropped
[languageServers.robotcode]
cmd = ["robotcode", "language-server"]
languages = ["robot", "resource"]
rootMarkers = ["robot.toml", "pyproject.toml", "Pipfile", ".git"]
