[languageServers.solargraph]
enabled = false
cmd = ["solargraph", "stdio"]
languages = ["ruby"]
workspaceMarkers = ["Gemfile", ".git"]
initializationOptions = { formatting = true }
settings = { solargraph = { diagnostics = true } }
