[languageServers.solidity]
enabled = false
cmd = ["solidity-ls", "--stdio"]
languages = ["solidity"]
rootMarkers = [".git", "package.json"]
settings = { solidity = { includePath = "", remapping = {} } }
