[languageServers.somesass_ls]
enabled = false
cmd = ["some-sass-language-server", "--stdio"]
languages = ["scss", "sass"]
rootMarkers = [".git", ".package.json"]
settings = { somesass = { suggestAllFromOpenDocument = true } }
